[package]
name = "bitwyre_logger"
version = "1.0.0-alpha.0"
authors = ["Aditya Kresna <aditya.kresna@outlook.co.id>"]
edition = "2021"

[dependencies]
env_logger = "=0.8.3"
log = { version = "=0.4.14", features = ["serde", "release_max_level_info", "max_level_debug"] }
